object Versions {
    const val appCompat = "1.3.1"
    const val core = "1.6.0"
    const val coroutines = "1.5.1"
    const val dokka = "1.4.30"
    const val hilt = "2.38.1"
    const val junit = "4.13.2"
    const val junitKtx = "1.1.2"
    const val kotlin = "1.5.30"
    const val lifeCycle = "2.3.1"
    const val material = "1.4.0"
    const val navigation = "2.3.5"
    const val okhttp = "4.9.1"
    const val retrofit = "2.9.0"
    const val recyclerView = "1.2.1"
    const val room = "2.3.0"
    const val espresso = "3.4.0"
}
